//
// Created by Revolware Company on 2019-09-06.
//

#include "CbInstructionTable.h"
#include "Instructions/Rotations.h"
#include "Instructions/Shifts.h"
#include "Instructions/Bit.h"

const Instruction::Handler CbInstructionTable[Instructions::InstructionsCount] = {
// 0x00
		RLC<B>,
		RLC<C>,
		RLC<D>,
		RLC<E>,
		RLC<H>,
		RLC<L>,
		RLC<IND<HL>, 16>,
		RLC<A>,
		RRC<B>,
		RRC<C>,
		RRC<D>,
		RRC<E>,
		RRC<H>,
		RRC<L>,
		RRC<IND<HL>, 16>,
		RRC<A>,
// 0x10
		RL<B>,
		RL<C>,
		RL<D>,
		RL<E>,
		RL<H>,
		RL<L>,
		RL<IND<HL>, 16>,
		RL<A>,
		RR<B>,
		RR<C>,
		RR<D>,
		RR<E>,
		RR<H>,
		RR<L>,
		RR<IND<HL>, 16>,
		RR<A>,
// 0x20
		SLA<B>,
		SLA<C>,
		SLA<D>,
		SLA<E>,
		SLA<H>,
		SLA<L>,
		SLA<IND<HL>, 16>,
		SLA<A>,
		SRA<B>,
		SRA<C>,
		SRA<D>,
		SRA<E>,
		SRA<H>,
		SRA<L>,
		SRA<IND<HL>, 16>,
		SRA<A>,
// 0x30
		SWAP<B>,
		SWAP<C>,
		SWAP<D>,
		SWAP<E>,
		SWAP<H>,
		SWAP<L>,
		SWAP<IND<HL>, 16>,
		SWAP<A>,
		SRL<B>,
		SRL<C>,
		SRL<D>,
		SRL<E>,
		SRL<H>,
		SRL<L>,
		SRL<IND<HL>, 16>,
		SRL<A>,
// 0x40
		BIT<B, 0>,
		BIT<C, 0>,
		BIT<D, 0>,
		BIT<E, 0>,
		BIT<H, 0>,
		BIT<L, 0>,
		BIT<IND<HL>, 0, 16>,
		BIT<A, 0>,
		BIT<B, 1>,
		BIT<C, 1>,
		BIT<D, 1>,
		BIT<E, 1>,
		BIT<H, 1>,
		BIT<L, 1>,
		BIT<IND<HL>, 1, 16>,
		BIT<A, 1>,
// 0x50
		BIT<B, 2>,
		BIT<C, 2>,
		BIT<D, 2>,
		BIT<E, 2>,
		BIT<H, 2>,
		BIT<L, 2>,
		BIT<IND<HL>, 2, 16>,
		BIT<A, 2>,
		BIT<B, 3>,
		BIT<C, 3>,
		BIT<D, 3>,
		BIT<E, 3>,
		BIT<H, 3>,
		BIT<L, 3>,
		BIT<IND<HL>, 3, 36>,
		BIT<A, 3>,
// 0x60
		BIT<B, 4>,
		BIT<C, 4>,
		BIT<D, 4>,
		BIT<E, 4>,
		BIT<H, 4>,
		BIT<L, 4>,
		BIT<IND<HL>, 4, 16>,
		BIT<A, 4>,
		BIT<B, 5>,
		BIT<C, 5>,
		BIT<D, 5>,
		BIT<E, 5>,
		BIT<H, 5>,
		BIT<L, 5>,
		BIT<IND<HL>, 5, 16>,
		BIT<A, 5>,
// 0x70
		BIT<B, 6>,
		BIT<C, 6>,
		BIT<D, 6>,
		BIT<E, 6>,
		BIT<H, 6>,
		BIT<L, 6>,
		BIT<IND<HL>, 6, 16>,
		BIT<A, 6>,
		BIT<B, 7>,
		BIT<C, 7>,
		BIT<D, 7>,
		BIT<E, 7>,
		BIT<H, 7>,
		BIT<L, 7>,
		BIT<IND<HL>, 7, 16>,
		BIT<A, 7>,
// 0x80
		RES<B, 0>,
		RES<C, 0>,
		RES<D, 0>,
		RES<E, 0>,
		RES<H, 0>,
		RES<L, 0>,
		RES<IND<HL>, 0, 16>,
		RES<A, 0>,
		RES<B, 1>,
		RES<C, 1>,
		RES<D, 1>,
		RES<E, 1>,
		RES<H, 1>,
		RES<L, 1>,
		RES<IND<HL>, 1, 16>,
		RES<A, 1>,
// 0x90
		RES<B, 2>,
		RES<C, 2>,
		RES<D, 2>,
		RES<E, 2>,
		RES<H, 2>,
		RES<L, 2>,
		RES<IND<HL>, 2, 16>,
		RES<A, 2>,
		RES<B, 3>,
		RES<C, 3>,
		RES<D, 3>,
		RES<E, 3>,
		RES<H, 3>,
		RES<L, 3>,
		RES<IND<HL>, 3, 36>,
		RES<A, 3>,
// 0xa0
		RES<B, 4>,
		RES<C, 4>,
		RES<D, 4>,
		RES<E, 4>,
		RES<H, 4>,
		RES<L, 4>,
		RES<IND<HL>, 4, 16>,
		RES<A, 4>,
		RES<B, 5>,
		RES<C, 5>,
		RES<D, 5>,
		RES<E, 5>,
		RES<H, 5>,
		RES<L, 5>,
		RES<IND<HL>, 5, 16>,
		RES<A, 5>,
// 0xb0
		RES<B, 6>,
		RES<C, 6>,
		RES<D, 6>,
		RES<E, 6>,
		RES<H, 6>,
		RES<L, 6>,
		RES<IND<HL>, 6, 16>,
		RES<A, 6>,
		RES<B, 7>,
		RES<C, 7>,
		RES<D, 7>,
		RES<E, 7>,
		RES<H, 7>,
		RES<L, 7>,
		RES<IND<HL>, 7, 16>,
		RES<A, 7>,
// 0xc0
		SET<B, 0>,
		SET<C, 0>,
		SET<D, 0>,
		SET<E, 0>,
		SET<H, 0>,
		SET<L, 0>,
		SET<IND<HL>, 0, 16>,
		SET<A, 0>,
		SET<B, 1>,
		SET<C, 1>,
		SET<D, 1>,
		SET<E, 1>,
		SET<H, 1>,
		SET<L, 1>,
		SET<IND<HL>, 1, 16>,
		SET<A, 1>,
// 0xd0
		SET<B, 2>,
		SET<C, 2>,
		SET<D, 2>,
		SET<E, 2>,
		SET<H, 2>,
		SET<L, 2>,
		SET<IND<HL>, 2, 16>,
		SET<A, 2>,
		SET<B, 3>,
		SET<C, 3>,
		SET<D, 3>,
		SET<E, 3>,
		SET<H, 3>,
		SET<L, 3>,
		SET<IND<HL>, 3, 36>,
		SET<A, 3>,
// 0xe0
		SET<B, 4>,
		SET<C, 4>,
		SET<D, 4>,
		SET<E, 4>,
		SET<H, 4>,
		SET<L, 4>,
		SET<IND<HL>, 4, 16>,
		SET<A, 4>,
		SET<B, 5>,
		SET<C, 5>,
		SET<D, 5>,
		SET<E, 5>,
		SET<H, 5>,
		SET<L, 5>,
		SET<IND<HL>, 5, 16>,
		SET<A, 5>,
// 0xf0
		SET<B, 6>,
		SET<C, 6>,
		SET<D, 6>,
		SET<E, 6>,
		SET<H, 6>,
		SET<L, 6>,
		SET<IND<HL>, 6, 16>,
		SET<A, 6>,
		SET<B, 7>,
		SET<C, 7>,
		SET<D, 7>,
		SET<E, 7>,
		SET<H, 7>,
		SET<L, 7>,
		SET<IND<HL>, 7, 16>,
		SET<A, 7>
};

const char CbInstructionNameTable[Instructions::InstructionsCount][Instructions::MaxInstructionNameSize] = {
// 0x00
		"RLC<B>",
		"RLC<C>",
		"RLC<D>",
		"RLC<E>",
		"RLC<H>",
		"RLC<L>",
		"RLC<IND<HL>, 16>",
		"RLC<A>",
		"RRC<B>",
		"RRC<C>",
		"RRC<D>",
		"RRC<E>",
		"RRC<H>",
		"RRC<L>",
		"RRC<IND<HL>, 16>",
		"RRC<A>",
// 0x10
		"RL<B>",
		"RL<C>",
		"RL<D>",
		"RL<E>",
		"RL<H>",
		"RL<L>",
		"RL<IND<HL>, 16>",
		"RL<A>",
		"RR<B>",
		"RR<C>",
		"RR<D>",
		"RR<E>",
		"RR<H>",
		"RR<L>",
		"RR<IND<HL>, 16>",
		"RR<A>",
// 0x20
		"SLA<B>",
		"SLA<C>",
		"SLA<D>",
		"SLA<E>",
		"SLA<H>",
		"SLA<L>",
		"SLA<IND<HL>, 16>",
		"SLA<A>",
		"SRA<B>",
		"SRA<C>",
		"SRA<D>",
		"SRA<E>",
		"SRA<H>",
		"SRA<L>",
		"SRA<IND<HL>, 16>",
		"SRA<A>",
// 0x30
		"SWAP<B>",
		"SWAP<C>",
		"SWAP<D>",
		"SWAP<E>",
		"SWAP<H>",
		"SWAP<L>",
		"SWAP<IND<HL>, 16>",
		"SWAP<A>",
		"SRL<B>",
		"SRL<C>",
		"SRL<D>",
		"SRL<E>",
		"SRL<H>",
		"SRL<L>",
		"SRL<IND<HL>, 16>",
		"SRL<A>",
// 0x40
		"BIT<B, 0>",
		"BIT<C, 0>",
		"BIT<D, 0>",
		"BIT<E, 0>",
		"BIT<H, 0>",
		"BIT<L, 0>",
		"BIT<IND<HL>, 0, 16>",
		"BIT<A, 0>",
		"BIT<B, 1>",
		"BIT<C, 1>",
		"BIT<D, 1>",
		"BIT<E, 1>",
		"BIT<H, 1>",
		"BIT<L, 1>",
		"BIT<IND<HL>, 1, 16>",
		"BIT<A, 1>",
// 0x50
		"BIT<B, 2>",
		"BIT<C, 2>",
		"BIT<D, 2>",
		"BIT<E, 2>",
		"BIT<H, 2>",
		"BIT<L, 2>",
		"BIT<IND<HL>, 2, 16>",
		"BIT<A, 2>",
		"BIT<B, 3>",
		"BIT<C, 3>",
		"BIT<D, 3>",
		"BIT<E, 3>",
		"BIT<H, 3>",
		"BIT<L, 3>",
		"BIT<IND<HL>, 3, 36>",
		"BIT<A, 3>",
// 0x60
		"BIT<B, 4>",
		"BIT<C, 4>",
		"BIT<D, 4>",
		"BIT<E, 4>",
		"BIT<H, 4>",
		"BIT<L, 4>",
		"BIT<IND<HL>, 4, 16>",
		"BIT<A, 4>",
		"BIT<B, 5>",
		"BIT<C, 5>",
		"BIT<D, 5>",
		"BIT<E, 5>",
		"BIT<H, 5>",
		"BIT<L, 5>",
		"BIT<IND<HL>, 5, 16>",
		"BIT<A, 5>",
// 0x70
		"BIT<B, 6>",
		"BIT<C, 6>",
		"BIT<D, 6>",
		"BIT<E, 6>",
		"BIT<H, 6>",
		"BIT<L, 6>",
		"BIT<IND<HL>, 6, 16>",
		"BIT<A, 6>",
		"BIT<B, 7>",
		"BIT<C, 7>",
		"BIT<D, 7>",
		"BIT<E, 7>",
		"BIT<H, 7>",
		"BIT<L, 7>",
		"BIT<IND<HL>, 7, 16>",
		"BIT<A, 7>",
// 0x80
		"RES<B, 0>",
		"RES<C, 0>",
		"RES<D, 0>",
		"RES<E, 0>",
		"RES<H, 0>",
		"RES<L, 0>",
		"RES<IND<HL>, 0, 16>",
		"RES<A, 0>",
		"RES<B, 1>",
		"RES<C, 1>",
		"RES<D, 1>",
		"RES<E, 1>",
		"RES<H, 1>",
		"RES<L, 1>",
		"RES<IND<HL>, 1, 16>",
		"RES<A, 1>",
// 0x90
		"RES<B, 2>",
		"RES<C, 2>",
		"RES<D, 2>",
		"RES<E, 2>",
		"RES<H, 2>",
		"RES<L, 2>",
		"RES<IND<HL>, 2, 16>",
		"RES<A, 2>",
		"RES<B, 3>",
		"RES<C, 3>",
		"RES<D, 3>",
		"RES<E, 3>",
		"RES<H, 3>",
		"RES<L, 3>",
		"RES<IND<HL>, 3, 36>",
		"RES<A, 3>",
// 0xa0
		"RES<B, 4>",
		"RES<C, 4>",
		"RES<D, 4>",
		"RES<E, 4>",
		"RES<H, 4>",
		"RES<L, 4>",
		"RES<IND<HL>, 4, 16>",
		"RES<A, 4>",
		"RES<B, 5>",
		"RES<C, 5>",
		"RES<D, 5>",
		"RES<E, 5>",
		"RES<H, 5>",
		"RES<L, 5>",
		"RES<IND<HL>, 5, 16>",
		"RES<A, 5>",
// 0xb0
		"RES<B, 6>",
		"RES<C, 6>",
		"RES<D, 6>",
		"RES<E, 6>",
		"RES<H, 6>",
		"RES<L, 6>",
		"RES<IND<HL>, 6, 16>",
		"RES<A, 6>",
		"RES<B, 7>",
		"RES<C, 7>",
		"RES<D, 7>",
		"RES<E, 7>",
		"RES<H, 7>",
		"RES<L, 7>",
		"RES<IND<HL>, 7, 16>",
		"RES<A, 7>",
// 0xc0
		"SET<B, 0>",
		"SET<C, 0>",
		"SET<D, 0>",
		"SET<E, 0>",
		"SET<H, 0>",
		"SET<L, 0>",
		"SET<IND<HL>, 0, 16>",
		"SET<A, 0>",
		"SET<B, 1>",
		"SET<C, 1>",
		"SET<D, 1>",
		"SET<E, 1>",
		"SET<H, 1>",
		"SET<L, 1>",
		"SET<IND<HL>, 1, 16>",
		"SET<A, 1>",
// 0xd0
		"SET<B, 2>",
		"SET<C, 2>",
		"SET<D, 2>",
		"SET<E, 2>",
		"SET<H, 2>",
		"SET<L, 2>",
		"SET<IND<HL>, 2, 16>",
		"SET<A, 2>",
		"SET<B, 3>",
		"SET<C, 3>",
		"SET<D, 3>",
		"SET<E, 3>",
		"SET<H, 3>",
		"SET<L, 3>",
		"SET<IND<HL>, 3, 36>",
		"SET<A, 3>",
// 0xe0
		"SET<B, 4>",
		"SET<C, 4>",
		"SET<D, 4>",
		"SET<E, 4>",
		"SET<H, 4>",
		"SET<L, 4>",
		"SET<IND<HL>, 4, 16>",
		"SET<A, 4>",
		"SET<B, 5>",
		"SET<C, 5>",
		"SET<D, 5>",
		"SET<E, 5>",
		"SET<H, 5>",
		"SET<L, 5>",
		"SET<IND<HL>, 5, 16>",
		"SET<A, 5>",
// 0xf0
		"SET<B, 6>",
		"SET<C, 6>",
		"SET<D, 6>",
		"SET<E, 6>",
		"SET<H, 6>",
		"SET<L, 6>",
		"SET<IND<HL>, 6, 16>",
		"SET<A, 6>",
		"SET<B, 7>",
		"SET<C, 7>",
		"SET<D, 7>",
		"SET<E, 7>",
		"SET<H, 7>",
		"SET<L, 7>",
		"SET<IND<HL>, 7, 16>",
		"SET<A, 7>"
};
